FROM python:3.8-slim-buster
WORKDIR /workdir
COPY src src
COPY data data
RUN pip3 install -r src/requirements.txt
CMD [ "python3", "-u", "-m" , "flask", "--app", "src/serve", "run", "--host=0.0.0.0", "--port=8000" ]